### ISSUE TITLE
Closing Eiry dialogue with the small x on the right upper side hangs

### ISSUE THREAD

**Issue by tkiapril** [aura-project/aura#220] opened 2016-01-19 17:07 UTC
Title has said about this issue almost all, when you open Eiry (/ key) and close the dialogue with the small x button on the right upper side, the client hangs. Possibly a bug?

BTW, [End Conversation] does properly close the window.

**Comment by exectails** [comment] 2016-01-19 17:15
I can't reproduce this, can you tell me more?

I talk to Eiry, and no matter where I am in the dialog, when I click the x button, the dialog closes, and I can continue to play.

Could this be related to the recent crashes with the NA client? Though I've only heard of Mailboxes and cutscenes being problematic so far. Then again, Eiry doesn't exist anymore, so nobody but us would know.

**Comment by tkiapril** [comment] 2016-01-19 17:20
These are my irregularities: I just downloaded the NA client yesterday. I copied the client from the original path that Launcher had installed, but I don't think it would be relevant to this issue. Also, I'm running the server in linux, by building with xbuild(mono) and mono runtime. Should I create some screencast to show the issue?

For the details, I could not explain more. All I know is that when I open Eiry with / key and press x, the client hangs without closing the window.

**Comment by exectails** [comment] 2016-01-19 17:27
I don't think a screencast will be necessary. The problem *sounds* straight forward, I just can't reproduce it. The NA client recently had problems with certain actions on Windows 8/10 though, I wonder if this is related.

Could someone else try this, maybe someone who does have those NA client problems?

**Comment by tkiapril** [comment] 2016-01-19 17:29
Yup, no coincidence I'm on Windows 8.1. Maybe someone with latest client could try to reproduce the issue?

**Comment by DeleteIT** [comment] 2016-01-19 17:32
Can you close it successfully with the `/` key, just out of curiosity?

Do any packets get sent on either event?

**Comment by ImaBrokeDude** [comment] 2016-01-19 17:33
Running Windows 10, no issues with Eiry closing, unable to reproduce.

**Comment by tkiapril** [comment] 2016-01-19 17:37
@DeleteIT Nuh, hangs. Never tried capturing the packets, will try.

**Comment by DeleteIT** [comment] 2016-01-19 17:42
I've had some issues with clients in windows 8, where they're actually working on loading something, but taken absolute ages to get it done, and look like they're not responding at all (and windows says as much).

Usually, if you wait, they'll continue on as normal.
Can take minutes to resolve itself though, I recommend just leaving it open one time, and seeing if it does eventually get over it.

**Comment by tkiapril** [comment] 2016-01-19 17:55
Dunno why, but never been able to get through character list screen with Morrighan. Will try to leave it to close on itself.

**Comment by DeleteIT** [comment] 2016-01-19 17:57
Do you have any mods/patchers/crackshield, by the way?

**Comment by tkiapril** [comment] 2016-01-19 17:58
Nope, fresh as it was downloaded by the official launcher.

**Comment by exectails** [comment] 2016-01-19 17:59
>Nuh, hangs

Does the client only hang once you click the X, or does it actually hang before? Are you able to talk to her normally, selecting "Ask for Help", etc?

>Nope, fresh as it was downloaded

Did you update it?

**Comment by DeleteIT** [comment] 2016-01-19 18:00
Apparently, if you close the chat via a conversational close button, instead of "forcing" the chat to close, the client will be okay with it.

**Comment by tkiapril** [comment] 2016-01-19 18:03
Actually, as @DeleteIT suggested, I waited for some minutes, and the window thaws back to me! After that, strangely both x and / works. What the heck.

@exectails after when I click on the x, it plays *beep-bop* and then hangs. Ask for Help, Ask for Question etc. works. It was probably updated (not sure), as it was downloaded by the Nexon Launcher, the one with fancy pages and multiple games to open.

Something suggests me that this is a client bug. :P

**Comment by DeleteIT** [comment] 2016-01-19 18:06
It's to do with loading/caching data then, something about Win 8.1 fills the client with such terrible rage, and if your GPU isn't super up to date, just loading the NPC face textures is an issue on Win 8.1

**Comment by tkiapril** [comment] 2016-01-19 18:08
@DeleteIT I should work with ramdisk and external GPU then, XD

**Closed** 2016-01-21 11:31 UTC
Labels: client problem
