### ISSUE TITLE
Monster AI crash while pet unsummon during fights with monster

### ISSUE THREAD

**Issue by garryrry** [aura-project/aura#429] opened 2016-09-14 07:02 UTC
I unsummon my pet while the pet is "fighting" with monsters.
The monster wont stop as it should be. It just like kind of searching for target. Then, Server crash

[Error] - AI.Attack: Unhandled combat skill result (InvalidTarget).
[Error] - AI.Attack: Unhandled combat skill result (InvalidTarget).

**Comment by exectails** [comment] 2016-09-14 09:23
Thanks for the report. Were there any other errors? While that error should clearly be fixed, it shouldn't crash the server. Was there a larger error/exception by any chance?

**Comment by garryrry** [comment] 2016-09-14 09:42
There is nothing else when i check back the log.
I have try replicate the bug again, but it didn't crash. (maybe the crash didnt related to the bug :) )
Just monsters searching for targets blindly

**Comment by exectails** [comment] 2016-09-14 10:34
Just to be sure, by crash do you mean the channel server just closing down?

**Comment by garryrry** [comment] 2016-09-14 11:23
Yes, the channel server closing down

**Closed** 2016-09-14 11:31 UTC
Labels: bug

**Comment by exectails** [comment] 2016-09-14 11:35
I've fixed the invalid target handling, so I'll close this for now, since we both couldn't reproduce the crash, which potentially was unrelated. It's weird there was no exception or error regarding the crash in the log file o~o

**Comment by garryrry** [comment] 2016-09-14 23:12
Ohh I finally replicate it. I just summon my pet and then right click the monster to call the pet to attack it. Then, the pet attack the monster it twice(bear isn't knockdown), then i unsummon the pet. Immediately, i got kick out with "30s notice" and my server goes down.

```
[Error] - Unable to send packet to 'XXX.XXX.XXX.XXX:9301'. (The object was used after being disposed.)
[Warning] - Client 'XXX.XXX.XXX.XXX:9301' : Account 'XXXXXXXXX' (Controlling 'Curry') just committed a Severe offense. Incident report: GetCreatureSafe: Client doesn't control creature 0x10010000000002
[Info] - Killed connection from 'XXX.XXX.XXX.XXX:9301'.
```

**Comment by exectails** [comment] 2016-09-15 08:42
Thanks, I've the kick now, but this still doesn't explain the crash, which I'm not experiencing o~o
