### ISSUE TITLE
Can't give Earring to Duncan

### ISSUE THREAD

**Issue by BentonNCo** [aura-project/aura#457] opened 2016-10-12 14:02 UTC
During the first quest of G1, I am trying to give the Earring back to Duncan, but it doesn't seem to be possible, it just ignores me and starts a normal conversation.

I assured I was the one that got the Earring from the snowman and not any pet, I already tried with other characters but I can't complete it in any way.

**Comment by exectails** [comment] 2016-10-12 15:32
Just to confirm, you do currently have the quest "Finding the Lost Earring", which you get shortly after logging in on a level 5+ character, after the Morrighan cutscene, and the earring is in your inventory?

**Comment by BentonNCo** [comment] 2016-10-12 15:34
Yes, I got the quest after the Goddess cutscene, after relogging when I got to level 5+

**Comment by Sairii** [comment] 2016-10-12 16:26
Works for me just fine.

**Comment by exectails** [comment] 2016-10-14 20:50
The official quest only has one objective though, which is to get the earring to Duncan =<

**Comment by Sairii** [comment] 2016-10-15 09:59
Yes I was able to complete the quest.
Also my g1 quest has 2 objectives, I logged that shit.
But might be because my quest is the new one?

**Comment by exectails** [comment] 2016-10-15 10:33
Yea, they added and removed several quests/objectives.

**Comment by exectails** [comment] 2016-10-15 12:16
@BentonNCo I have to ask again, since you didn't clearly confirm this yet, do you have the earring that you got from the snowman in your inventory?

I've just tested it as well, and I had no issue getting the earring and completing the quest by talking to Duncan normally. It might sound silly, but could you walk us through what you're doing step by step? Since this is the first report of this, and we confirmed that it's working for others, we must assume that it's either an unusual bug/glitch, for which we need more information, or that you might be doing something wrong.

**Comment by exectails** [comment] 2016-10-17 20:51
@BentonNCo Any new information?

**Comment by exectails** [comment] 2016-10-31 19:31
Gonna close this for now, since there's not enough information to reproduce it.

**Closed by exectails** 2016-10-31 19:31 UTC
Labels: can't reproduce

**Comment by exectails** [comment] 2016-11-13 20:46
Today I had problems giving the earring to Duncan, and I briefly thought I had encountered this bug, when I realized I just had like 4 quests for Duncan queued up, and I had to go through all of them before he would finally take the earring. But I was able to give it to him in the end.
