### ISSUE TITLE
Beginner Hunting Quest: Kill 1 Red Bear

### ISSUE THREAD

**Issue by Zanathkariashi** [aura-project/aura#242] opened 2016-02-25 15:07 UTC
[1000049_hunting_red_bear.zip](https://github.com/aura-project/aura/files/146772/1000049_hunting_red_bear.zip)

The beginner quest Kill 1 Red Bear has improper syntax.

it uses "/redbear/" instead of "/red bear/" and doesn't properly register kills from red bears.

uploaded the corrected script file

**Comment by Cosrnos** [comment] 2016-02-25 15:14
Thanks for contributing! You may want to submit this as a pull request to make it easier to review the code changes and merge into the core (plus then you get listed as a contributor on github!)

**Comment by Zanathkariashi** [comment] 2016-02-25 15:52
No idea how to do that.

**Comment by exectails** [comment] 2016-02-25 17:39
Hum. Actually, `/redbear/` should be correct o.o
```
{ id: 70002, name: "Red Bear", group: "bear/none", tags: "/animal/bear/beast/redbear/"
```
You're saying the quest worked *after* your change?

**Comment by Zanathkariashi** [comment] 2016-02-25 21:15
correct. I killed 20 red bears with no change, and went and checked some of the other hunting quests and the ones with 2 words always had spaces but red bear didn't. So I changed that since I didn't see anything else that would work and it counted my next kill after reloading the servers.

Apparently it looks at the Name part of the race register and not the tag section for those quests.

**Comment by QewQew** [comment] 2016-02-26 01:08
Stock files.
Hunted a red bear.
Counted.

**Comment by exectails** [comment] 2016-02-26 08:53
I have yet to test it, but I don't see anything in the code that would suggest a bug. Just to be sure: You did kill Red Bears, right? Not like Red Grizzly Bears? But even then it, it shouldn't work after your change...

**Comment by Zanathkariashi** [comment] 2016-02-26 12:14
yeah, I was mostly kiling the red bears around Reighalt but it didn't work, and I hadn't looked at quest script yet i so I figured maybe it wanted red bears from a specific area, so I went to the logging camp and kill the ones around there for awhile since that's where the marker was, and still nothing. So I finally I decided to find that script and looked through it till I found which part was the requirement and then went and looked through the red bear section of the races, and it didn't seem to be wrong, but I just on whim tried adding a space to match the name section and the very next kill after reloading the server gave me credit.
 

    On Friday, February 26, 2016 3:53 AM, exec <notifications@github.com> wrote:
 

 I have yet to test it, but I don't see anything in the code that would suggest a bug. Just to be sure: You did kill Red Bears, right? Not like Red Grizzly Bears? But even then it, it shouldn't work after your change...—

**Comment by exectails** [comment] 2016-02-26 13:10
I can't reproduce it. I don't know what went wrong, but I don't think it was the objective. Could you test it again on a second character?

![mabinogi_2016_02_26_001](https://cloud.githubusercontent.com/assets/5593920/13353085/255ef35a-dc92-11e5-9217-fe519ce04fcd.jpg)
![mabinogi_2016_02_26_002](https://cloud.githubusercontent.com/assets/5593920/13353086/2568896a-dc92-11e5-9fc8-0e89ed5224e7.jpg)

**Comment by DeleteIT** [comment] 2016-02-26 21:26
Why is the "Complete" button black?
I didn't think the UI colour affected those, mine were always that golden yellow.

**Comment by QewQew** [comment] 2016-02-26 21:28
The Gold Yellow button was from the old UI.

**Comment by DeleteIT** [comment] 2016-02-26 21:35
Really? They have that in the coloured DDS UIs now?

**Comment by exectails** [comment] 2016-03-08 12:51
I'll close this for now, as it couldn't be reproduced and there hasn't been an update for almost 2 weeks. Feel free to comment here if there's any news, and I'll reopen the issue.

**Closed by exectails** 2016-03-08 12:51 UTC
Labels: bug, unconfirmed
