### ISSUE TITLE
Are you able to catch even bigger fish?

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#433] opened 2016-09-16 16:29 UTC
_There's something I don't quite understand about fishing._

As you rank up every now and then, it's mentioned "you are able to catch even bigger fish now". I've always been able to catch 150 cm Brifne carps from Rank F, but now I'm Rank 4 and I'm still not catching anything bigger than that. Is there a reason for this? On the wiki there's also a fish size multiplier, but it feels like it's left out.

While at this topic - are all the sizes valued as 10g in resell value? I can't remember if there is a difference in the officials.

_Reference:_
http://wiki.mabinogiworld.com/view/Fishing

**Comment by exectails** [comment] 2016-09-17 09:14
Brifne Carps have a min size of 10cm and a max size of 150cm. We don't know the official formulas, but the way it's implemented in Aura, you can always catch any size, but an increased rank gives you a bonus in min size, which allows you to catch bigger fish more easily. The Wiki calls that bonus "Fish Size Modifier". Another bonus is the "Automatic Fishing Size", which increases the min size further on Aura.

I don't know about their selling value, I've probably fished more on Aura while testing the skill handler than I ever did on officials.

**Comment by exectails** [comment] 2016-09-17 19:48
I asked someone who fishes a lot, and apparently they do sell for different prices. I'll think about a way to incorporate that.

Now the size. Should there be bigger Brifne Carps than 150cm? Should they be limited, so you *can't* catch the max size below a certain rank? Or is our formula fine? It's a little hard to tell without extensive research, aka catching boatloads of Carps on various Fishing ranks.

**Comment by Pegwald** [comment] 2016-09-17 21:16
if you ask for my opinion, I mean that maybe the 150 cm carps should only be obtainable at R1, unless you can get bigger ones in the officials.

**Comment by exectails** [comment] 2016-09-17 21:24
Well, I'd prefer to have it the way it is on officials of course^^

Looking at it logically, I don't think there's a reason why a really big fish shouldn't be attracted to your bait with rF Fishing. The difficulty should lie in actually getting it out of the water, i.e. the mini-game. The server can actually modify the speed of the fish in the mini-game, maybe that's something we want to do.

**Comment by Pegwald** [comment] 2016-09-17 22:15
Oh, but in that case - I understand the logic in that :)

**Comment by exectails** [comment] 2016-09-19 07:01
I'll close this for now, since what we have works as intended, the only question might be if it's 100% official behavior. This is the case for many of our custom formulas though. If someone gets new information on this, that suggests our theory might be wrong, just comment here.

**Closed by exectails** 2016-09-19 07:01 UTC
Labels: bug, unconfirmed
