### ISSUE TITLE
Intermittent Issue with Ais

### ISSUE THREAD

**Issue by Yumiser** [aura-project/aura#329] opened 2016-06-27 15:08 UTC
This has been happening with a few of the AIs, this one is just an example.

```
2016-06-27 06:51 [Exception] - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Aura.Channel.Scripting.Scripts.AiScript.SelectState()
   at Aura.Channel.Scripting.Scripts.AiScript.Heartbeat(Object state)
```

**Comment by exectails** [comment] 2016-06-27 16:03
Could you elaborate under which circumstances this happens? Does it happen frequently, which AIs, etc.

**Comment by boilerplate5** [comment] 2016-06-27 16:36
I know it's not super helpful but I can't confirm this. Everything's run smoothly for me in about 25~ hours of gameplay.

**Comment by Yumiser** [comment] 2016-06-27 19:14
Well for this particular one two things happened around the time of that exception:

- A player killed another creature (fox) a chicken was fighting
- Another player DC'd because of #328

They were both in the general area. (Tir Square)

It's happening mostly with foxes and hens, but seems to be triggered by something else (Possibly #328) so it's kinda infrequent but is of course happening.

Sorry I'm not much use on giving more information ):
Thanks!

**Comment by exectails** [comment] 2016-06-27 20:26
I don't see a problem in the code, but if this happened multiple times there must be something to it... you're sure it was this exact exception that you saw multiple times, right?

It's unlikely to be related to #328, as that was a problem with a quest not being found in the database, completely unrelated to AIs.

**Comment by exectails** [comment] 2016-09-13 14:27
I will close this for now, since we couldn't reproduce it and it apparently hasn't occurred for the past few months. Should someone encounter it again, we'll pick this back up.

**Closed by exectails** 2016-09-13 14:27 UTC
Labels: bug, unconfirmed
