### ISSUE TITLE
Pets share exact same skills, no race-specifics.

### ISSUE THREAD

**Issue by Natje0** [aura-project/aura#398] opened 2016-08-29 16:29 UTC
All pets possess only the skills "Combat Mastery" at rank F, as well as an unlearnt Critical hit.

Pets that should have special skills, such as the White Flame Spider, do not possess those skills, instead having the aforementioned skills.

New skills are not learnt on level up. (Only tested to level3)

**Comment by exectails** [comment] 2016-08-29 16:38
Thanks for the report. As mentioned on the forum, pets haven't really been implemented yet. You can create and summon them, and give them basic commands, but that's about it. As such it's to be expected that many functions related to them aren't working properly or at all.

I'll mention the pet issue #18 here, to reference this issue, and close it for now, as it's not a bug, but a part of the pet backlog issue, that is to be implemented in G2.

**Closed by exectails** 2016-08-29 16:38 UTC
