### ISSUE TITLE
Eating dishes not giving EXP for Cooking Skill

### ISSUE THREAD

**Issue by posilepton** [aura-project/aura#467] opened 2016-11-02 12:08 UTC
For levelling up cooking you must eat/cook differently made foods in order to get exp. There's something going on where it doesn't recognize you eating stuff for ranking up and making delicious simmered foods for rank E.

**Comment by exectails** [comment] 2016-11-02 15:29
Hi, thanks for your report. I've just tested it, and I got training for eating simmered food. Is it possible the quality of the food you tried was below 4 stars? Since the training requirement is to eat a *perfectly* simmered dish, you won't get training for anything below that.

**Comment by posilepton** [comment] 2016-11-03 00:45
The issue is with eating the next tier of food for the hidden requirement, specifically "Eat a X dish without sharing.".

**Comment by eotetb** [comment] 2016-11-03 04:06
I did have an issue trying to get training on Rank F for eating a perfectly baked dish, it was 5 stars and played a cut-scene (roasted turkey to be specific). Of course I'm not sure if its really a bug, I think I remember official being really finicky. On another note, I got training for perfectly baking an item, but did not get any training for just baking an item.

**Comment by exectails** [comment] 2016-11-03 08:27
Isn't the "without sharing" training always for meals you can't cook yourself yet? I've just tried simmering something, ranked down to F, and ate it, I got training for the eat without sharing condition, as expected.

Do you have concrete examples?

**Comment by eotetb** [comment] 2016-11-03 15:44
`if (method == CookingMethod.Baking)
				{
					if (rating == DeliciousRating)
						skill.Train(1); // Make a dish that is deliciously baked.
					else
						skill.Train(2); // Successful in baking a dish.
				}`
They way this code is now, if you were to bake something perfectly it stops you from getting any training from just baking any item successfully.

The skill should give training for "Successful in baking a dish" in addition to the "Make a dish that is deliciously baked" requirement.

Something like this makes sense to me:
`if (method == CookingMethod.Baking)
				{
					if (rating == DeliciousRating)
						skill.Train(1); // Make a dish that is deliciously baked.
                                                skill.Train(2); // Successful in baking a dish.
					else
						skill.Train(2); // Successful in baking a dish.
				}`

**Comment by eotetb** [comment] 2016-11-03 16:10
Alright, I see why the training didn't work for eating a perfectly baked dish. It does not seem to work with some 2 ingredient dishes for whatever reason (in this case, the roasted turkey). I tried again with a different dish (fried egg) and it worked fine. According to the wiki, that's how it works on official as well:

"Some two-ingredient-recipes count as a "Eat a deliciously [cooking method] food" for eating or cooking and some do not. For example, Fried Egg does not, but Steamed Corn does."

That's sort of annoying, but at least its working the way its "supposed" to.

**Comment by eotetb** [comment] 2016-11-03 16:22
Also, confirmed what @posilepton said about the hidden requirement "Eat a X dish without sharing."

I ate a Hard-Boiled Egg at rank F, which should give points for the "Eat a simmered dish without sharing." requirement. However, I received no training from that.

**Comment by exectails** [comment] 2016-11-03 18:37
>That's sort of annoying, but at least its working the way its "supposed" to.

If both had 4 stars they should definitely contribute to eating a deliciously baked/simmered food in Aura though o.o

>I ate a Hard-Boiled Egg at rank F, [...] However, I received no training from that.

Eh? But that's exactly what I did earlier, and it worked o.o We are talking about self-made food here, right?

**Comment by Sairii** [comment] 2016-11-03 19:01
>However, I received no training from that.

You sure you recompiled?

**Comment by eotetb** [comment] 2016-11-03 21:17
> If both had 4 stars they should definitely contribute to eating a deliciously baked/simmered food in Aura though o.o

[Unfortunately it did not.](https://youtu.be/bh1OzWJXJPg)
And sorry, the video is a little bit crude, but it shows me eating a roasted turkey that is 5 stars that I crafted and consumed. I ended up not getting any training for that, but I did when I consumed a fried egg right afterwards. I believe this is an issue in official as well.

>Eh? But that's exactly what I did earlier, and it worked o.o We are talking about self-made food here, right?

I'm sorry, I tried to do the requirement with an item I spawned. I tried again with an item I crafted and it worked. I forgot that the item had to be player made to count towards the training.

**Comment by exectails** [comment] 2016-11-03 22:44
Oh, it has to be *exactly* 4 stars, not 5. I guess that's a bug? =P

**Comment by eotetb** [comment] 2016-11-04 00:17
@exectails 
Actually, that really does seem to be the problem. I ate another roasted turkey that was 4 stars and did receive the training. Of course I have yet to test a different dish at 4 stars, but it seems to be the case anyways.

**Comment by exectails** [comment] 2016-11-04 08:46
I've fixed the 5 star problem in 941722492e6b22bc7d6e24c34a0859a7be07a430, and under the assumption that that was the bug we were searching for, I'm going to close this issue. Thanks for the help finding the problem.

**Closed by exectails** 2016-11-04 08:46 UTC
Labels: bug
