### ISSUE TITLE
Counter Attack Issue (walking)

### ISSUE THREAD

**Issue by Managus** [aura-project/aura#525] opened 2016-12-22 07:35 UTC
when i use counter attack, the creature still walking by clicking...

**Comment by QewQew** [comment] 2016-12-22 07:49
![image](https://cloud.githubusercontent.com/assets/11168098/21418731/103bc124-c7d8-11e6-8e7b-ab5fe5200451.png)
Are you equipping a sword/blunt/axe?

**Comment by exectails** [comment] 2016-12-22 08:25
Mhm, that's a G19 feature I believe? It's currently activated by default, in combination with the new combat.
https://github.com/aura-project/aura/blob/master/system/db/features.txt#L737

**Comment by exectails** [comment] 2016-12-25 21:56
I'll close this for now, as it seems likely that the feature setting is the cause.

**Closed by exectails** 2016-12-25 21:56 UTC
Labels: expected behavior, unconfirmed
