### ISSUE TITLE
Default Pose bug

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#89] opened 2015-11-09 01:58 UTC
When you first log in to Aura, you're put in some sort of default stiff-looking pose. Apparently [you can trigger this on NA](http://mabination.com/threads/85756-(Amusing)-Mabinogi-Bugs?p=1289403&viewfull=1#post1289403) if you do certain things.

But yeah the pose is unnatural.

**Comment by exectails** [comment] 2015-11-09 11:48
What do you mean by "when you first log in"? I don't think I've ever seen this.

**Comment by Xcelled** [comment] 2015-11-09 19:15
After logging in on NA:
![](http://puu.sh/lftcK/a07302e26c.jpg)

After logging in on Aura:
![](http://puu.sh/lfthE/1f76704a74.jpg)

After taking one step on Aura:
![](http://puu.sh/lftjC/916e105555.jpg)

**Comment by exectails** [comment] 2015-11-09 19:29
I think I've seen characters stand like that on the char selection screen, didn't notice it in-game yet. But... I don't have a single clue what might be causing this... It could very well be some weird glitch in the client, that we will never be able to fix. Should we even declare this a "bug", and keep it around in an issue? =/

**Comment by Xcelled** [comment] 2015-11-09 19:52
It happens 100% of the time on Aura, and 0% of the time on NA. Seems like a bug to me.

Tho Rydian's being able to trigger it with a rest hack might indicate it's somehow related to rest?

**Comment by exectails** [comment] 2015-11-09 20:19
>It happens 100% of the time on Aura, and 0% of the time on NA. Seems like a bug to me.

Doesn't mean that it's Aura's fault, we're talking about something that devCAT developed. The client crashes if you don't wait till everything on the char selection is loaded, that usually doesn't happen on NA either.

**Comment by QewQew** [comment] 2015-11-09 20:28
>that usually doesn't happen on NA either.

Actually it happens on NA. I usually get this less often on Aura since I only have a few characters on the account compared to NA.

**Comment by Xcelled** [comment] 2015-11-09 20:49
My point is *something* is different between NA and Aura. Maybe it's a missing packet, or an out-of-order send, but there has to be a reason this doesn't happen on NA.

**Comment by exectails** [comment] 2015-11-11 11:15
>Maybe it's a missing packet, or an out-of-order send

That would make it easily reproducible though =/ Half the time when I log in I don't have that problem.

**Comment by Xcelled** [comment] 2015-11-13 07:38
Ahh, I just noticed something. It only happens once per client start. Relogging won't trigger the pose, but restarting the client *will*. In a quick test, the bug happened 0/3 times when relogging, but 3/3 when restarting.

Could this indicate a problem with the login server? Some sort of pose data not being sent on the login screen, but which the client automatically fills later and then 'reuses'?

**Comment by exectails** [comment] 2015-11-13 12:15
>Relogging won't trigger the pose, but restarting the client will. 

That doesn't match my own findings, I *did* restart the client on every of my three tries, *because* the client tends to cache some stuff. One of these tries didn't put me in the stiff pose.

>Could this indicate a problem with the login server?

It's an interesting theory, but I wouldn't think so. The data you get on the login server is a bare minimum (CreaturePacketType.Minimal) to display the character. We do ignore many of the values in that packet, which we might want to change at some point, but nothing I would think might cause this.

**Comment by exectails** [comment] 2016-01-19 19:09
The login server on NA doesn't always put them in the correct state either:
![](http://puu.sh/mBNZh/1d1a018b3c.jpg)

**Comment by exectails** [comment] 2016-01-24 16:39
I keep thinking that this is probably some obscure glitch, that we can't really fix. I can't produce it reliably, and while I haven't seen it *in-game* on NA yet, I regularly see it on the char selection.

**Comment by exectails** [comment] 2016-03-08 15:24
Has anyone else ever taken a look at this?

**Comment by exectails** [comment] 2016-06-01 09:20
I'll close this, as it can't be reproduced reliably and I don't see how it could even be caused by Aura. If anyone wants to share their experience on this, or has an idea what might be causing it or how it can be fixed, we can reopen the issue.

**Closed by exectails** 2016-06-01 09:20 UTC
Labels: bug, unconfirmed
