### ISSUE TITLE
G1 RP moves party members to Jail

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#487] opened 2016-11-27 14:54 UTC
_I'm just going to paste this link here._

[link removed]

**Comment by exectails** [comment] 2016-11-27 15:44
Thanks for the report, but please refrain from posting links to private server sites here.

I've already removed the "security exception -> jail" feature just now, in f9e12ecda56c9b1dc9c7484b925a422e33f12e9c, so that shouldn't happen anymore. What I'm curious about though is why exactly that happened, what the client did to trigger the security exception.

Could you take a look at your logs (files and database) to try to find the one responsible for this?

**Comment by exectails** [comment] 2016-11-29 09:38
I'll close this, since I wasn't able to reproduce it and I removed what caused it, but I'm still interested in the core issue, what exactly the client did to trigger the security exception.

**Closed by exectails** 2016-11-29 09:38 UTC
Labels: bug
