### ISSUE TITLE
Missing door in Fiodh int-

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#163] opened 2015-12-26 12:01 UTC
When doing Fiodh int. for 2 we were missing a door. We couldn't find it, but we were still able to proceed to the boss room. It was still locked, though, cause we got a message saying we had to open all doors or whatever. We had the key, but the room did not spawn :l

**Comment by exectails** [comment] 2015-12-26 12:11
We're checking if there are any closed doors in the entire dungeon, and [according to Tachi](https://github.com/aura-project/aura/issues/71#issuecomment-155435324), doors should only be on the critical path, so you shouldn't be able to get to the boss door without passing all doors. In theory.

Could you look up the log file? There should be a Debug log for when the dungeon was created, with the parameters that were used. Using those parameters we can take a look at that exact dungeon instance you saw.

\*puts up the @Tachiorz -signal*

**Comment by Pegwald** [comment] 2015-12-26 12:29
[ChannelServer.txt](https://github.com/aura-project/aura/files/72438/ChannelServer.txt)

Here you go :>

**Comment by exectails** [comment] 2015-12-26 13:43
I just ran the dungeon without any issues o.o Cleared every room, found the boss room key like 3 rooms before the boss, and I could simply open the boss room door with it.

**Comment by Pegwald** [comment] 2015-12-26 14:31
what??
I don't understand anything. I got the boss key 1-2 rooms before the boos, 3rd floor had 3 herb rooms and well... we had a bonus key on 1st floor.

**Comment by Pegwald** [comment] 2015-12-26 16:20
Is it possible to open a door and keep a key? I can remember my party mate "Jun" picking up a blue key, then opening a blue lock 2 rooms away from the next floor...
Maybe that's not the issue since we needed a door and not a key, but how is it possible that we failed the run and you did not? You did use the same seed, right?

**Comment by DeleteIT** [comment] 2015-12-26 16:23
That would have still left you with all the doors open. The server only cares if the door is shut, not if you still have the key.

The only thing about having the key left over, is that perhaps the door's state didn't change to open.

@exectails server collision is in, right?

Also, Tachi said in the post you quoted
> Each door guards either main path ***or another mandatory puzzle on sub path.***

Because doors *DEFINITELY* do not have to go anywhere useful.

**Comment by DeleteIT** [comment] 2015-12-26 16:33
@Pegwald Maybe take a look at the dungeon map with Pale, and see if there's any area you recall not visiting?

**Comment by exectails** [comment] 2015-12-26 16:34
>we had a bonus key on 1st floor

A spare key...? I didn't notice anything. I just ran the first floor again, and I needed every key to get to the end. And I'm pretty I've been in every room both times. And yes, I did use your seed. That was the point after all^^"

>perhaps the door's state didn't change to open.

If the state didn't change to open, the door wouldn't have opened. Server collisions for players aren't in, but they would've probably noticed if they had walked through a closed door, because the state is coupled to the visuals.

>Also, Tachi said in the post you quoted
>>Each door guards either main path or another mandatory puzzle on sub path.
>Because doors DEFINITELY do not have to go anywhere useful.

Of course they do o.o You have to go through every door to advance, either by actually advancing, or by getting a key to advance. Okay, technically they aren't all on the critical path, but they're all required to clear it.

**Comment by exectails** [comment] 2015-12-26 16:36
>Is it possible to open a door and keep a key? I can remember my party mate "Jun" picking up a blue key, then opening a blue lock 2 rooms away from the next floor...

No, I don't see how that would be possible. The door will only open once the item was removed from the inventory.

**Comment by DeleteIT** [comment] 2015-12-26 16:39
I'm pretty sure I've unlocked a door that lead to a corridor.
Which lead to *nothing.*

It stands out, because we milled around for a moment, confused, as we're used to doors leading places.

**Comment by exectails** [comment] 2015-12-26 16:40
On *Aura*?

**Comment by DeleteIT** [comment] 2015-12-26 16:41
No, I've literally never done a dungeon on Aura.
I thought we were talking about dungeons generally.

**Comment by exectails** [comment] 2015-12-26 16:42
Nah, the official implementation isn't really important to this problem.

**Comment by DeleteIT** [comment] 2015-12-26 16:46
Maybe a command to dump all the dungeon information to a text file would be useful?
The statuses of all the doors/keys/mob groups/chests, for example.

**Comment by exectails** [comment] 2015-12-26 16:51
Yea, maybe, but the person reporting an issue probably wouldn't use it, we'd still have to run the dungeon. Afterwards it might be of use, but in this instance for example, I can't reproduce it, so I don't have a use for the command either.

**Comment by DeleteIT** [comment] 2015-12-26 17:36
Which is why I said to tie it to the dungeon door being unable to be opened message, so they don't have a choice, the dump happens when that failure occurs.

**Comment by exectails** [comment] 2015-12-26 17:37
Oh, missed that.

**Comment by exectails** [comment] 2016-01-04 19:23
Just now I thought it had happened to me in Albey, I was already mad that I didn't implement the command, but I had simply missed a door, because I mainly used the mini map warp to move from room to room =P

But you were probably playing legit, right?

**Comment by Pegwald** [comment] 2016-01-04 22:22
Yep, no super GM powers involved. Just two regular characters

**Comment by exectails** [comment] 2016-01-24 16:35
Since I couldn't reproduce this issue, even though I ran the exact dungeon you had twice, and nobody else has reported such a problem yet, I'll close this issue for now. Should you encounter this problem again, just comment here or create another issue.

**Closed by exectails** 2016-01-24 16:35 UTC
Labels: bug, unconfirmed

**Comment by Pegwald** [comment] 2016-01-25 01:36
Got it
