### ISSUE TITLE
Unsaved skillchange after rebirth

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#114] opened 2015-11-29 13:07 UTC
I tried to rebirth right after leveling up and ranking production mastery, but after the rebirth the production mastery skill was still at its previous rank, but the AP I spent was still spent. Could this be the channel not saving my skills before the rebirth and loading an old state? I don't get it, cause I still lost 10 ap.

**Comment by Pegwald** [comment] 2015-11-29 13:08
I solved my issue by simply closing down the channel server and rerunning it, but I still believe we have to fix this bug.

**Comment by exectails** [comment] 2015-11-29 13:12
So... you rebirthed, the rank was wrong, you restarted the channel, and the rank was right? That's virtually impossible, unless there was an error, which would be visible in the channel window/log file. There is no "loading an old state", everything is loaded/saved at once, and there is only that one state.

Are you 100% sure that's what happened? o,o

**Comment by Pegwald** [comment] 2015-11-29 13:47
This is what happened! I guess things wasn't quite synchronized so I forced down the channel, not saving my character, then restarted it.
I don't quite understand this either, but people I know say this very often - "Sometimes there's just something wrong that isn't quite right!" ^^''

**Comment by exectails** [comment] 2015-11-29 21:25
I really don't see how that would be possible... especially since you're saying your AP were saved. Did you check the log file from that session for errors?

**Comment by Pegwald** [comment] 2015-11-29 21:27
no, the AP was still spent, not saved. And I also did not check the log file for errors. Can I still manage to find that in archive?

**Comment by exectails** [comment] 2015-11-29 21:30
Of course, that's what the archive is for.

>no, the AP was still spent, not saved.

That's what I mean, the *new* AP amount was saved.

**Comment by Pegwald** [comment] 2015-11-29 21:32
Oh, then I get it. I will look around and see if I find anything

**Comment by Pegwald** [comment] 2015-11-29 21:48
Here's an update on what I found in the archive - "nothing". "Nothing" as in "nothing useful or abnormal here". I don't get it.

**Comment by exectails** [comment] 2016-01-24 16:31
Has this happened again to anyone in the past 2 months?

**Comment by exectails** [comment] 2016-03-08 15:20
I'm closing this for now. Apparently it hasn't happened again in the past months and I still don't see how it would be possible, maybe it was really weird glitch, caused by god knows what, and we'll never see it again. *Should* it happen again to anybody, please comment here.

**Closed by exectails** 2016-03-08 15:20 UTC
Labels: bug, unconfirmed
