### ISSUE TITLE
Alby Intermediate for 4 Bug - Giant Black Spider dying Hangs Client

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#317] opened 2016-06-21 05:00 UTC
The picture is the log in the Channel Server window. It warns about a darkred_spider when entering the boss room. The [Error] comes up when the Black Spider is KO'd.
http://puu.sh/pAhx3/875df48e23.jpg

I've only been able to complete Alby Intermediate for Four once. Any subsequent attempts end up hanging the client after the Giant Black Spider is defeated. This forces the player to relog to regain control. As the log shows, Windmill was the final attack, but another case involves using Ranged Attack.

**Comment by exectails** [comment] 2016-06-21 06:37
This issue is caused by an enchant that is added to a treasure chest when you beat the boss, the dungeon script attempted to use an enchant suffix as a prefix. This should be fixed now, thanks for the report.

**Closed by exectails** 2016-06-21 06:37 UTC
Labels: bug
