### ISSUE TITLE
Cooking Stuff

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#416] opened 2016-09-10 07:14 UTC
Glenis is supposed to sell items like strawberries, shrimp, and other 1x1 ingredients in increments of 1, 5, 10, and 20. Carrots and Tomatoes aren’t set like this currently, only sold as one item for four entries.

You have to separate items from the stack. If you try to use the whole stack it consumes the whole stack. Bug?

**Incorrect percentage shown in game** means that the item can be made but can’t be done due to what is specified on the wiki and/or possesses percentages that are absurd or impossible (like 75% berry and 90% strawberry) that will fail without a hidden third ingredient.

~Items of Issue~
**MIXING**
Mixed Fruit/Assorted Fruits
Strawberry 45%, Apple 31%, Berry 24%
Incorrect percentage shown in game.

Potato Salad
Steamed Potato 69%, Onion 22%, Salt 9%
Incorrect percentage shown in game.

Potato & Egg Salad
Steamed Potato 55%, Hard-Boiled Egg 35%, Mayonnaise 10%
Incorrect percentage shown in game.

Onion Fried Tuna
Bluefin Tuna 67.5%, Onion 32.5%
Bluefin Tuna 60%, Onion 30%, Salt 10%
Bluefin Tuna 60%, Onion 30%, Garlic 10%
All combinations of the dish do not work and thus food waste is produced.

Club Sandwich
Sliced Bread 50%, Tomato 20%, Cabbage 30%
Item order is out of place in-game and percentages are off.

Leighean Sling
Lemonade 73%, Leighean Gin 19%, Sugar 8%
Combination fails, always produces waste.

**KNEADING**
No Issues

**MAKE NOODLES**
No issues

**PASTA MAKING**

Long Pasta
Water 80%, Pasta Dough 20%
Combination fails, always produces waste.

**PIE MAKING**
No issues

**BAKING**

Bacon Wrapped Tuna
Bluefin Tuna 60%, Bacon 35%, Pepper 5%
Combination fails, always produces waste.

**SIMMERING**
No issues.

**BOILING**
Potential server crash issue when eating food from this tree. Corrupts character stats and requires a restart. Not sure yet. It happened again with Steaming as well.

Espresso
Water 80%, Roasted Coffee 20%
Combination fails, always produces waste.

Silver Vine Tea
Silvervine Fruit 10%, Water 90%
Combination fails, always produces waste.

Thyme Tea
Water 90%, Thyme 10%
Combination fails, always produces waste.

**DEEP-FRY**
No issues.

**STIR FRY**
No issues.

**JAM MAKING**
No issues.

**STEAMING**
No issues with the food but can potentially cause a server crash by corrupting character data. Still not sure what exactly causes it but in the future people will need to be on the lookout.

**Comment by exectails** [comment] 2016-09-10 08:20
Thanks for the detailed report, fixed the sell amounts in 81298a1dbdbcbae9cea3de36323cca292f7c2d2b.

Now for the amounts. First up
>Incorrect percentage shown in game

Technically, since the client displays this based on its own local data, the percentage shown can't be incorrect. Similar to repair costs, the server has to be adjusted to the client. That being said, the cooking db is updated every time I update the other dbs, after every Mabi update, so the data is most definitely correct.

By the looks of it, the problem is in our interpretation of the data. For example:
>Mixed Fruit/Assorted Fruits
Strawberry 45%, Apple 31%, Berry 24%

The data has the following values: 70%, 50%, and 40%. Obviously that doesn't add up to 100, but our Cooking skill handler operates under the assumption that it does. As a result, your ingredients are way off, and you can't get a good result.

I'll push a change that should fix it, please give it a try.

**Comment by boilerplate5** [comment] 2016-09-10 08:57
It lists as 75%, 50%, and 40%  now :V

For the most part a lot of the stuff was over 100% in ingredients terms but I stopped reporting on it because I assume anybody who does cooking is going to be looking it up on the wiki and use the ruler, especially due to some of the hidden third ingredients. My thought process was that it mattered more if the item could be made at all and I covered all of the failing foods.

**Comment by exectails** [comment] 2016-09-10 09:05
>It lists as 75%, 50%, and 40% now :V

Huh...? You mean prior to the fix the client displayed what you first reported, and now it displays that...? That would be a client bug. Like I said, the server doesn't send *any* data to the client in regards to ingredients, the client takes it all from its own data.

**Comment by exectails** [comment] 2016-09-10 09:08
The calculations *should* be correct now though, so no matter what the client displays, you should get the expected results.

**Comment by exectails** [comment] 2016-09-11 08:20
I'll close this, since it *should* work fine now. Just comment here again if it doesn't.

**Closed by exectails** 2016-09-11 08:20 UTC
Labels: bug
